language: node_js
node_js:
  - node
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    'on':
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    'on':
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
env:
  matrix:
    - secure: >-
        NV5TEAZh5s3DDBxUEusDzaZgc9uVO9IwQtCjcWxQI97TLJCdTTVbc/+mMVOA6bQ+aad8K4PczXQK7F5CLZ8Dz8lS20AHN0h9+YHOOh5wCVx+PYwK+zqdQx1miiIob+1Xh4Ggs74w4ZocUxIgwIfsrqBUVcFqdsWt7VilgG9DJNS4iXvEKY23vGO24EdQY8qGSbHhGNXoCtJcnCjRuGNf96sjR0f7Ve0CaU5QzMOxNvMtm4FDNdDO2gP+nslp4NQqcuqUi2lqWT5OBl5HpT3ZUUfm13pWZLOdOfi4kVOH5nkDGGgFbze6Av4r2zkXYTIukYMdbXSxdoIXGqaFbTINHcd+XwW777pe5YWiOzeDKYW9koB4vg+YHX7NtIRyg5rqsOPnmLE0EDzOIqq7GXEkf07jBTqFWqs/TofVak5oQ1WoQeG1lxfL6E6ZNqh52OBOKDZaf+fB9DccSOHiuiGEuZarZctlvmORkRJNaD/E2l1sUB2FTPMmLySBmT0KeLk/RREdVaulG04+ej9Wge93Dkm+KuizQ2i5vzNmXD41e4mVzw/g6pIofZfaZ/3GeG9nrUpM80LNIByx7AO9+nljYnkfASj3p5mBFbMJrTGDy1TY49Q9KhJFURKHtzrs/wy08MfT4dna5MA/M+UqioKVTmT3UVVTDu6Wu0XNYQvowNE=
