language: node_js
node_js:
  - node
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    'on':
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    'on':
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
env:
  matrix:
    - secure: >-
        BifqES8C5Ao+XsI4R/oCe8Qp+vRRlGJeTAjV6ZT55+c8+oc+wvtobc03ALMl+jEYp58WzyH/3RoeUkWu9MOLKh/dTXnHYFrlWc82yCVGG4UQkAfSDR+icr/KCRM75czYyU7AjA79Q/u0IoKaou0JLr5QW3EqdXtmOo3X4V7c/W4cOFWKyi2wF7EHDUNZ/tSoKlk94sTfPAkFcz2+OXNQAgNUvTJGm1OTH1MYjUj1pau34HNEBMNbzRGgui1ZPb93T6B33WxO8B4bJfuW12rnoXjAWMz9TNV34UTWl5iNqL4OuC7iiXIAzzbSXoC3qiL4JPgORAan6a+hwxXQjYqRiUM9v/le7LyKneEmW4cUQFtInZCBbOxBPPQchVs7KX3EtNayZBLX3e78OMNAZl5NHF8RHjJOZko01D6BVwuBPIm+kgue8SnicQzPRJuftBt7QMxPBOMOJj8ZNbgNNu8I3ljd/v1BdnmVOGKElQeTQ9Gh7JWVVozepTXOzieDPrAFVYSW1nASdDO5aBraoNsaSUzmBQKHHQtUcaqBU4xwpBzPk9hxZxPTdTQbwToH6Lt/faSJeEivIJEmzZYKDKReTalkLie//m1rIO8kimmSC0LheiZvRe3jQ+rSgDtx+jrhkH1ILspIr9xndkBF/JNPEVmewYMcobPU68guS092HZk=
