language: node_js
node_js:
  - node
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    'on':
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    'on':
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
env:
  matrix:
    - secure: >-
        HQ00+zEUz9gNMjNcqpkM0QVd93+1hnZGLMMzrUcxx0ggioz3J475ADhcOZ0GAW3lw0r/5Yhk5emhN4lOLTW+okbYzsy3Oc+BdiOoyCWuqaslfA185R243ueUnlIcTklZ3MNUr6KRVv1kApfrf5ewQL5SiaHtTH1M9szrgyALUy9ou/yiw+sdUf7DzFxILyQN3vUFXaG8JpZu+TNXc3cPTBin6s8nYCL/aJF7JuaifU0tnCGfB/vWjA6dFlLCvSXzj/plzYMZ9W/NichQnOC+knOY2s16FPejC6pD0EPHUgcusGQnf/IpGvAa95mu0haXRRNDSTqDXhVeKYxUHU0vFw7KPUA3E3TO0hyf0/Rt8b4F7VR4dC/GeEH3zh3IPhWkuq6+VqweFNHh2Eq++jD7y/3FSAavVA6FsOSYzZFOZounibT2PKBkjW0ZXR4JYbY7HEdZGckaqHzAL7Y3xUGxh4/zSUyyA05An4oTrN/0llwrEMqrhxjzNbT54XbsjmVYdd1AB6F2ieySfP3L5/OeJdPKMJQqoes7hh3jNsm0NGtO7Ctl8M0o0GXquKtJp7KfkEZMTb9nrKjt25PwwLsVV5vq0C82omRh4/uACl1TOCdwSiOoYjtNwG2v8dMHFlhu7HxC5VS5G9v0cEuAFc9U3S+XYKrG47pMsDG1I3oLnok=
